parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  project: "./tsconfig.json"
  tsconfigRootDir: "./"
env:
  browser: true
  es6: true
plugins:
  - "@typescript-eslint"
extends:
  - "standard"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  quotes:
    - warn
    - single
  indent:
    - warn
    - 4
    - SwitchCase: 1
  semi:
    - warn
    - always
  comma-dangle:
    - warn
    - always-multiline
  spaced-comment:
    - warn
  array-bracket-spacing:
    - warn
    - always
  multiline-ternary: 0
  "react-hooks/rules-of-hooks":
    - error
  "react-hooks/exhaustive-deps": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-member-accessibility": 0
  "@typescript-eslint/ban-ts-ignore": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/ban-ts-comment": 0
  "react/prop-types": 0
  "react/display-name": 0
  "react/jsx-indent-props":
    - warn
    - 4
  "react/jsx-boolean-value":
    - warn
    - never
  "react/jsx-closing-bracket-location":
    - 1
    - "line-aligned"
  "react/jsx-closing-tag-location": 1
  no-use-before-define: 0
  "@typescript-eslint/no-use-before-define":
    - warn
overrides:
  - files:
      - "**/*.tsx"
    rules:
      operator-linebreak:
        - error
        - before
        - overrides:
            "&&": "after"
            "?": "ignore"
            ":": "ignore"